language: android
dist: trusty
#dist: bionic
jdk: oraclejdk8

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ANDROID_ABI=armeabi-v7a
  - NODE_ENV=testing

addons:
  apt:
    sources:
      - sourceline: deb https://dl.yarnpkg.com/debian/ stable main
        key_url: https://dl.yarnpkg.com/debian/pubkey.gpg
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/.npm
    - ~/.npm
    - ~/.yarn-cache
    - travis_phantomjs
    - node_modules    

before_install:
    - touch $HOME/.android/repositories.cfg
    - yes | sdkmanager "platforms;android-28"
    - yes | sdkmanager "build-tools;28.0.3"
    - export LANG=en_US.UTF-8

# before_script:
  # - chmod +x gradlew

script: 
  # See https://austinpray.com/ops/2015/09/20/change-travis-node-version.html

  # Clear out whatever version of NVM Travis has.
  # Their version of NVM is probably old.
   - rm -rf ~/.nvm

  # Grab NVM.
   - git clone https://github.com/creationix/nvm.git ~/.nvm 
  # Checkout the latest stable tag.
  # Note that you can just hardcode a preferred version here.
   - (cd ~/.nvm; git checkout `git describe --abbrev=0 --tags`)

  # Add nvm command available to shell
   - source ~/.nvm/nvm.sh

  # Install a lts version of Node
   - nvm install --lts
   - npm install -g ionic
   - npm install -g cordova
   - npm test
  # - npm ci
  # - ionic cordova platform add android
  # - ionic cordova build android
  # - ./gradlew clean build
  # - ./gradlew test  
  
branches:
  only:
    - master
    - /^greenkeeper-.*$/
