language: android

android:
  components:
  - platform-tools
  - tools
  - build-tools-21.1.1
  - android-21

sudo: false

branches:
  only:
    - master
    - /^greenkeeper-.*$/

node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - lts/*
  - node

os:
  - windows
  - linux
  - osx

matrix:
  allow_failures:
    - os: windows
    
env:
  - NODE_ENV=testing

cache:
  directories:
    - $HOME/.npm
    - ~/.npm
    - ~/.yarn-cache
    - travis_phantomjs
    - node_modules

script:
  - npm test
