language: android

android:
  components:
  - platform-tools
  - tools
  - build-tools-21.1.1
  - android-21

sudo: false

branches:
  only:
    - master

os:
  - linux
 
env:
  - NODE_ENV=testing

cache:
  directories:
    - $HOME/.npm
    - ~/.npm
    - ~/.yarn-cache
    - travis_phantomjs
    - node_modules	

install:
  matrix:
   - nvm install 4
   - nvm install 5
   - nvm install 6
   - nvm install 7

before_script:
  - npm install

script:
  - npm test
